### PR TITLE
feat(mcp): let operators disable individual built-in tools

### PR DESCRIPTION
**Pull request by vishal-bala**
`list-indexes`, `search-records`, and `upsert-records` all registered unconditionally, so an operator who wanted a narrower tool surface had no way to get one. A deployment that should never advertise writes still published `upsert-records` whenever any binding was writable, and a single-purpose server still published discovery.

## The config

```yaml
server:
  builtin_tools:
    upsert-records: disabled
```

Omitted names stay enabled, so **existing configs are unaffected**. Only the three real names are accepted: `search_records` with underscores fails at startup rather than silently disabling nothing while reading as though it had.

## Two unusable-but-valid tool surfaces now warn

Both shapes are legal config that presents to a client as a server that simply does not work, and both were previously silent:

- **Everything disabled** leaves a server that connects and offers nothing. The warning deliberately does not name a cause, since `upsert-records` can also be absent because every binding is read-only.
- **Discovery disabled on a multi-index server** leaves `search-records` demanding a logical index id that clients have no way to learn — its own description tells them to call `list-indexes` first.

Neither is fatal, because an operator may be mid-rollout.

The multi-index discovery case had **no coverage anywhere**, so this adds it, along with the negative case: with a sole binding the `index` argument defaults, so disabling discovery there is legitimate and stays quiet. I verified by mutation that the new test fails when the warning condition is neutered.

## Verification

- MCP unit tests: 237 passing
- `make check-types`: clean
- Pre-commit: passing

## Note on sequencing

This is independently useful and mergeable on its own. It is also a prerequisite for the custom tool profiles work that follows, since a profile name must be checked against the built-in names this PR introduces.

---

> [!NOTE]
> **Medium Risk**
> Changes which MCP tools clients see and discovery/write advertising; misconfiguration can yield empty or hard-to-use tool surfaces, though defaults preserve existing behavior and validation plus warnings reduce silent failures.
> 
> **Overview**
> Adds **`server.builtin_tools`** so operators can disable any of `list-indexes`, `search-records`, or `upsert-records` individually (omitted tools stay enabled). Unknown names fail at **startup** validation instead of being ignored.
> 
> **Registration** gates each built-in on config; **`list-indexes`** sets **`upsert_available`** to false when upsert is disabled even if bindings are writable. On **multi-index** servers with discovery off, **search** and **upsert** tool descriptions **inline** logical index ids. **Startup warnings** cover empty tool lists, discovery disabled with multiple indexes, and **config changes** after tools were already registered (process restart required to change the published surface).
> 
> Docs in **`docs/concepts/mcp.md`** describe the config and behavior.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit f323df5d4d9b4639e2f9550c8ab5558c6feb294c. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: redisvl/mcp/tools/list_indexes.py [hunk 1]
```diff
@@ -82,7 +82,11 @@ def list_indexes(server: "RedisVLMCPServer") -> dict[str, Any]:
 
 
 def register_list_indexes_tool(server: "RedisVLMCPServer") -> None:
-    """Register the always-available, read-only `list-indexes` MCP tool."""
+    """Register the read-only `list-indexes` MCP tool.
```
[the remark this answers is not in the document]
Comment (vishal-bala) [reply redisvl/mcp/tools/list_indexes.py:98]: Confirmed and fixed in 6018b3b — this one was the most directly harmful of the three.

`upsert_available` is a client-facing claim about what is *callable*, and it was derived from the binding's read-only state alone. Before this PR that derivation was correct, because `upsert-records` registered whenever any binding was writable. Adding the toggle broke the equivalence without updating the claim, so a writable binding on a server with the tool disabled reported `upsert_available: true` — and a client would only discover otherwise by attempting a write.

It now requires the tool to be published as well as the binding to be writable. Two tests: the disabled case, and a control with an explicit config that leaves the built-in on. Reverting only this fix makes the first one fail.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

File: redisvl/mcp/server.py [hunk 2]
```diff
@@ -282,17 +282,70 @@ def _register_tools(self) -> None:
...
+
+        registered: list[str] = []
+
+        # Discovery is on by default so clients can enumerate indexes.
+        if enabled("list-indexes"):
+            register_list_indexes_tool(self)
+            registered.append("list-indexes")
+        if enabled("search-records"):
+            register_search_tool(self, search_schema)
+            registered.append("search-records")
```
[the remark this answers is not in the document]
Comment (vishal-bala) [reply redisvl/mcp/server.py:339]: Confirmed and fixed in 6018b3b.

Worth being precise about why this was worse than a stale doc string: on a multi-index server `index` is *required*, and with `list-indexes` withheld the logical ids are otherwise unlearnable. So the published contract was not merely pointing at a missing tool — it was unsatisfiable.

`search-records` now names the available ids inline in exactly that case (multi-index **and** discovery disabled), which is the only way a client can obtain them. When discovery is available the description defers to it as before.

I kept the startup warning rather than treating the inline ids as a fix for the shape — inlining is a fallback, and an operator disabling discovery on a multi-index server still probably didn't mean to. Tests cover both branches, and reverting only this fix makes the disabled-discovery test fail.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

File: redisvl/mcp/server.py [hunk 3]
```diff
@@ -282,17 +282,70 @@ def _register_tools(self) -> None:
...
         # of which are folded into effective_read_only; the per-call write check
         # in the tool then rejects writes to any individual read-only binding.
-        if any(not rt.effective_read_only for rt in self._bindings.values()):
+        if enabled("upsert-records") and any(
+            not rt.effective_read_only for rt in self._bindings.values()
+        ):
             register_upsert_tool(self)
+            registered.append("upsert-records")
+
+        self._warn_on_unusable_tool_surface(registered)
```
[the remark this answers is not in the document]
Comment (vishal-bala) [reply redisvl/mcp/server.py:350]: Partly disagree on the diagnosis, but the underlying risk is real and it is now warned about — 6018b3b.

`_tools_registered` and its survival across teardown predate this PR: `main` carries an explicit comment that it is "intentionally *not* reset here," because re-registering the same names on the FastMCP object is not valid. So the flag is not a bug and I have not removed it — the once-per-process behavior is deliberate.

What this PR *does* change is whether that matters. Previously the tool set derived only from binding read-only state, which is re-derived on every `startup()`, so a reuse cycle could not go stale. Now it also depends on `builtin_tools`, and `startup()` re-reads the config file — so a stop/start against an edited config keeps the old tool set. That is a new consequence, and you're right to flag it.

Rather than reset the flag (which would break registration), the server now fingerprints the config its tools were built from and warns when a later registration attempt sees a different one. The dangerous direction is an operator disabling a tool, restarting, and believing it is gone.

Docs now state plainly that changing the tool surface requires a new process. Test covers the mismatch path; reverting only the warning makes it fail.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

File: redisvl/mcp/server.py [hunk 4]
```diff
@@ -282,17 +306,80 @@ def _register_tools(self) -> None:
...
+            # Without discovery the caller cannot learn the logical ids, so the
+            # description has to name them rather than pointing at a tool that is
+            # not published. Only relevant when the schema is ambiguous, which is
+            # exactly the multi-binding case.
+            unlisted_index_ids = (
+                sorted(self._bindings)
+                if search_schema is None and "list-indexes" not in registered
+                else None
+            )
+            register_search_tool(self, search_schema, index_ids=unlisted_index_ids)
```
[the remark this answers is not in the document]
Comment (vishal-bala) [reply redisvl/mcp/server.py:338]: Correct, and it was the cause of the Service Tests failure — fixed in c4d3485.

I fixed the two unit-test stubs when I changed the signature and did not grep the integration tests. That's the actual mistake: `monkeypatch.setattr` stubs only fail at call time, so an arity mismatch is invisible to type checking and to any suite that doesn't reach that line.

Verified rather than assumed. Reverting the stub reproduces the exact CI error:

```
>   register_search_tool(self, search_schema, index_ids=unlisted_index_ids)
E   TypeError: ...<lambda>() got an unexpected keyword argument 'index_ids'
```

Then audited every patched registration call site — five for `register_search_tool`, all now matching; `register_list_indexes_tool` and `register_upsert_tool` are unchanged so their stubs are still valid.

Also ran the full MCP integration suite locally this time (56 passed, 2 skipped), which is what would have caught this before pushing. My earlier local integration run was inconclusive due to a partial venv, so I was relying on CI for that layer — not doing that again for signature changes.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

File: redisvl/mcp/server.py [hunk 5]
```diff
@@ -282,17 +306,80 @@ def _register_tools(self) -> None:
...
         # Expose upsert only when at least one binding is writable. A binding is
         # read-only under global read-only mode or its own read_only policy, both
         # of which are folded into effective_read_only; the per-call write check
         # in the tool then rejects writes to any individual read-only binding.
-        if any(not rt.effective_read_only for rt in self._bindings.values()):
+        if enabled("upsert-records") and any(
+            not rt.effective_read_only for rt in self._bindings.values()
+        ):
             register_upsert_tool(self)
+            registered.append("upsert-records")
```
[the remark this answers is not in the document]
Comment (vishal-bala) [reply redisvl/mcp/server.py:348]: Both halves confirmed and fixed in f323df5. This is a gap I created in the previous commit — I fixed the unsatisfiable contract for `search-records` and left `upsert-records` with the identical defect.

**The inline ids.** Both tools require an `index` once several bindings exist, so both are stranded when `list-indexes` is withheld. Upsert was arguably worse off: its description never mentioned discovery at all, so a client had no route to the ids even in principle. `register_upsert_tool` now takes the same `index_ids`, and the condition is computed **once** in `_register_tools` and passed to both rather than derived per call site — which is exactly how the two drifted apart in the first place.

**The warning.** You're right that it was keyed on `search-records` alone, so a write-only surface with discovery off stayed silent. It now reports whichever index-requiring tools are actually published and names them, so the operator sees which ones are affected.

Each half has a test that fails when only that half is reverted — one asserting upsert receives the same ids as search, one asserting the warning fires and names `upsert-records` on a surface where search is disabled. Docs updated to describe the tool-agnostic behavior rather than search specifically.

Also ran the full MCP integration suite (56 passed, 2 skipped), not just unit — the previous signature change broke a stub only integration exercised, so that's part of the routine now.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

**Review by nkanu17 — APPROVED** [review]
lgtm!
